apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: rootpassword
        ports:
        - containerPort: 3306
        volumeMounts:                   
          - name: mysql-data
            mountPath: /var/lib/mysql   

      volumes:                          
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc

